{% set name = "pytest_executable" %}
{% set version = "0.5.0" %}

package:
  name: pytest-executable
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('_', '-') }}-{{ version }}.zip
  sha256: ca63890a5f9aa64834665f141d31301c3fd641187521dd466e045af1a7cd068b

build:
  number: 0
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pytest >=4.3,<6
    - pyyaml >=3,<6
    - jsonschema >=2,<4
    - jinja2 >=2.7,<3
    - delta ==0.4.*
    - dataclasses

test:
  requires:
    - pip
  commands:
    - python -m pip check
    - pytest --traceconfig | grep pytest-executable-{{ version }}
  imports:
    - pytest_executable

about:
  home: https://pytest-executable.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: pytest plugin for testing executables
  doc_url: https://github.com/CS-SI/pytest-executable
  dev_url: https://pytest-executable.readthedocs.io

extra:
  recipe-maintainers:
    - AntoineD
