{% set name = "pytest-executable" %}
{% set version = "0.5.6" %}

package:
  name: {{ name }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name.replace('-', '_') }}/{{ name }}-{{ version }}.tar.gz
  sha256: f61d428ed84c086e6fed14a9dc5a8bfd936c2d938ed525f52b4f80262a69804c

build:
  number: 2
  skip: true  # [win]
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - pip
    - python
  run:
    - python
    - pytest >=5,<8
    - pyyaml >=3,<6.1
    - jsonschema >=2,<5
    - jinja2 >=2.7,<3.2
    - delta >=0.4,<0.5

test:
  requires:
    - pip
  commands:
    - python -m pip check
  imports:
    - pytest_executable

about:
  home: https://pytest-executable.readthedocs.io
  license: Apache-2.0
  license_family: APACHE
  license_file: LICENSE.txt
  summary: pytest plugin for testing executables
  doc_url: https://pytest-executable.readthedocs.io
  dev_url: https://github.com/CS-SI/pytest-executable

extra:
  recipe-maintainers:
    - AntoineD
